In [1]:
import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt

In [2]:
cam=cv.VideoCapture(0)
while True:
    _,img=cam.read()
    img=cv.flip(img,1)
    cv.imshow("Original",img)
    if cv.waitKey(1)==27:
        cam.release()
        break

In [3]:
img.shape

(480, 640, 3)

In [4]:
img.mean()

np.float64(154.48297309027777)

In [5]:

img

array([[[ 98,  97, 101],
        [ 95,  94,  97],
        [ 97,  95,  98],
        ...,
        [169, 169, 169],
        [168, 168, 168],
        [168, 168, 168]],

       [[ 98,  96, 101],
        [ 95,  94,  98],
        [ 96,  95,  98],
        ...,
        [168, 168, 168],
        [168, 168, 168],
        [168, 168, 168]],

       [[ 96,  95, 101],
        [ 94,  93,  99],
        [ 95,  95,  99],
        ...,
        [168, 168, 168],
        [168, 168, 168],
        [168, 168, 168]],

       ...,

       [[192, 198, 214],
        [191, 198, 214],
        [191, 199, 215],
        ...,
        [ 59,  66,  63],
        [ 61,  66,  64],
        [ 61,  66,  64]],

       [[188, 198, 211],
        [189, 199, 212],
        [189, 201, 213],
        ...,
        [ 59,  63,  64],
        [ 60,  64,  65],
        [ 61,  64,  65]],

       [[189, 201, 212],
        [188, 201, 212],
        [188, 202, 213],
        ...,
        [ 58,  62,  64],
        [ 60,  63,  65],
        [ 61,  64,  66]]

In [6]:
img-20

array([[[ 78,  77,  81],
        [ 75,  74,  77],
        [ 77,  75,  78],
        ...,
        [149, 149, 149],
        [148, 148, 148],
        [148, 148, 148]],

       [[ 78,  76,  81],
        [ 75,  74,  78],
        [ 76,  75,  78],
        ...,
        [148, 148, 148],
        [148, 148, 148],
        [148, 148, 148]],

       [[ 76,  75,  81],
        [ 74,  73,  79],
        [ 75,  75,  79],
        ...,
        [148, 148, 148],
        [148, 148, 148],
        [148, 148, 148]],

       ...,

       [[172, 178, 194],
        [171, 178, 194],
        [171, 179, 195],
        ...,
        [ 39,  46,  43],
        [ 41,  46,  44],
        [ 41,  46,  44]],

       [[168, 178, 191],
        [169, 179, 192],
        [169, 181, 193],
        ...,
        [ 39,  43,  44],
        [ 40,  44,  45],
        [ 41,  44,  45]],

       [[169, 181, 192],
        [168, 181, 192],
        [168, 182, 193],
        ...,
        [ 38,  42,  44],
        [ 40,  43,  45],
        [ 41,  44,  46]]

In [7]:
import cv2 as cv
cam=cv.VideoCapture(0)
while True:
    _,img=cam.read()
    img=cv.flip(img,1)
    img1=img-100
    cv.imshow("Original",img)
    cv.imshow("Filter_1(img-100)",img1)
    
    if cv.waitKey(1)==27:
        cam.release()
        break

In [8]:
print("Shape of original image",img.shape)
print("Shape of filter image",img1.shape)

Shape of original image (480, 640, 3)
Shape of filter image (480, 640, 3)


In [9]:
print("mean of original image",img.mean())
print("mean of filter image",img1.mean())

mean of original image 150.84659288194445
mean of filter image 128.41881510416667


In [10]:
print("Values of original image",img)
print("Values of filter image",img1)

Values of original image [[[ 98  97  99]
  [101 100 102]
  [105 104 106]
  ...
  [163 162 165]
  [161 160 163]
  [159 158 161]]

 [[ 96  95  97]
  [ 98  97  99]
  [100  99 101]
  ...
  [164 163 165]
  [163 162 164]
  [162 161 163]]

 [[ 96  95  97]
  [ 97  96  98]
  [ 97  96  98]
  ...
  [165 165 166]
  [164 164 165]
  [164 164 165]]

 ...

 [[186 202 212]
  [186 202 212]
  [186 202 212]
  ...
  [ 68  68  68]
  [ 67  67  67]
  [ 65  65  65]]

 [[187 201 213]
  [187 201 213]
  [188 202 214]
  ...
  [ 68  69  67]
  [ 67  68  66]
  [ 65  66  64]]

 [[187 201 213]
  [188 202 214]
  [189 202 214]
  ...
  [ 68  69  66]
  [ 67  68  65]
  [ 67  68  65]]]
Values of filter image [[[254 253 255]
  [  1   0   2]
  [  5   4   6]
  ...
  [ 63  62  65]
  [ 61  60  63]
  [ 59  58  61]]

 [[252 251 253]
  [254 253 255]
  [  0 255   1]
  ...
  [ 64  63  65]
  [ 63  62  64]
  [ 62  61  63]]

 [[252 251 253]
  [253 252 254]
  [253 252 254]
  ...
  [ 65  65  66]
  [ 64  64  65]
  [ 64  64  65]]

 ...

 [[ 

In [11]:
import cv2 as cv
pixels=float(50)
cam=cv.VideoCapture(0)
while True:
    _,img=cam.read()
    img=cv.flip(img,1)
    img2=img*1.5
    img2[img2<0]=0
    img2[img2>255]=255
    img2=img2.astype(np.uint8)
    cv.imshow("Original",img)
    cv.imshow("Filter_2(img*1.5)",img2)
    
    if cv.waitKey(1)==27:
        cam.release()
        break

In [12]:
print("Shape of original image",img.shape)
print("Shape of filter image",img2.shape)

Shape of original image (480, 640, 3)
Shape of filter image (480, 640, 3)


In [13]:
print("mean of original image",img.mean())
print("mean of filter image",img2.mean())

mean of original image 153.26371419270833
mean of filter image 203.54224283854165


In [14]:
print("Values of original image",img)
print("-"*100)
print("Values of filter image",img2)

Values of original image [[[ 94  92  96]
  [ 95  93  97]
  [ 95  93  97]
  ...
  [168 171 163]
  [168 171 162]
  [168 171 162]]

 [[ 90  89  94]
  [ 91  90  95]
  [ 93  91  96]
  ...
  [168 170 163]
  [168 171 163]
  [168 171 162]]

 [[ 86  87  93]
  [ 87  88  94]
  [ 90  90  96]
  ...
  [167 169 163]
  [167 169 163]
  [167 169 162]]

 ...

 [[185 195 203]
  [184 195 203]
  [181 195 204]
  ...
  [ 64  68  67]
  [ 65  66  66]
  [ 65  65  65]]

 [[185 194 204]
  [183 194 204]
  [181 194 205]
  ...
  [ 63  67  66]
  [ 62  64  64]
  [ 61  62  62]]

 [[184 194 204]
  [183 194 205]
  [182 195 206]
  ...
  [ 61  65  64]
  [ 59  61  61]
  [ 57  59  59]]]
----------------------------------------------------------------------------------------------------
Values of filter image [[[141 138 144]
  [142 139 145]
  [142 139 145]
  ...
  [252 255 244]
  [252 255 243]
  [252 255 243]]

 [[135 133 141]
  [136 135 142]
  [139 136 144]
  ...
  [252 255 244]
  [252 255 244]
  [252 255 243]]

 [[129 130 13

In [15]:
import cv2 as cv
pixels = float(10)

cam = cv.VideoCapture(0)

while True:
    
    _, img = cam.read()
    img = cv.flip(img, 1)
    
    img_1 = img + pixels
    img_1[img_1 <  0 ] = 0
    img_1[img_1 > 255] = 255
    img_1 = img_1.astype(np.uint8)
    
    img_2 = img*1.5
    img_2[img_2 <  0 ] = 0
    img_2[img_2 > 255] = 255
    img_2 = img_2.astype(np.uint8)
    
    img_3 = img *2
    img_3[img_3 <  0 ] = 0
    img_3[img_3 > 255] = 255
    img_3 = img_3.astype(np.uint8)
    
    
    cv.imshow("Original",img)
    cv.imshow("Filter-1",img_1)
    cv.imshow("Filter-2",img_2)
    cv.imshow("Filter-3",img_3)
    
    if cv.waitKey(1) == 27:
        cam.release()
        break

In [16]:
import cv2 as cv
pixels = float(10)

cam = cv.VideoCapture(0)

while True:
    
    _, img = cam.read()
    img = cv.flip(img, 1)
    
    img_1 = img *0.9
    img_1[img_1 <  0 ] = 0
    img_1[img_1 > 255] = 255
    img_1 = img_1.astype(np.uint8)
    
    img_2 = img *0.7
    img_2[img_2 <  0 ] = 0
    img_2[img_2 > 255] = 255
    img_2 = img_2.astype(np.uint8)
    
    img_3 = img*0.5
    img_3[img_3 <  0 ] = 0
    img_3[img_3 > 255] = 255
    img_3 = img_3.astype(np.uint8)
    
    
    cv.imshow("Original",img)
    cv.imshow("Filter-1",img_1)
    cv.imshow("Filter-2",img_2)
    cv.imshow("Filter-3",img_3)
    
    if cv.waitKey(1) == 27:
        cam.release()
        break